{{- if .Values.neos.ingress.enabled -}}
{{- $fullName := (print .Release.Name "-neos") -}}
{{- $svcPort := .Values.neos.service.port -}}
{{- if and .Values.neos.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.neos.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.neos.ingress.annotations "kubernetes.io/ingress.class" .Values.neos.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "neos-ci.labels" . | nindent 4 }}
    app.kubernetes.io/component: neos
  {{- with merge (deepCopy .Values.neos.ingress.annotations) .Values.default.ingress.annotations .Values.default.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.neos.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.neos.ingress.className }}
  {{- end }}
  {{- if .Values.neos.ingress.tls }}
  tls:
    {{- range .Values.neos.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $hostname := .Values.neos.ingress.hostnames }}
    - host: {{ $hostname | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
